#pragma once



#include <string>
#include <unordered_map>
#include <vector>
#include <cstdint>


/**
 * @brief Represents a generic passive two-terminal component.
 *
 * The actual component type is determined by the first character of the
 * component name:
 *
 *      R* -> Resistor
 *      C* -> Capacitor
 *      L* -> Inductor
 *      I* -> Current source
 *
 * These components can be stored using a common representation because they
 * all share the same topology:
 *
 *      name
 *      positive node
 *      negative node
 *      value
 */
class PassiveComponent {
public:

    /**
     * Component identifier from the netlist.
     *
     * Examples:
     *
     *      R1
     *      C_load
     *      Lfilter
     */
    std::string name;

    /**
     * Internal index of the positive terminal.
     *
     * The index refers to the translated node numbering generated by the
     * parser.
     */
    int32_t positive_node;

    /**
     * Internal index of the negative terminal.
     *
     * Ground is represented using node index -1.
     */
    int32_t negative_node;

    /**
     * Component value.
     *
     * Depending on the component type this may represent:
     *
     *      Resistance   [Ohm]
     *      Capacitance  [F]
     *      Inductance   [H]
     *      Current      [A]
     */
    double value;

    /**
     * @brief Construct a new Passive Component object.
     *
     * @param name Component identifier.
     * @param positive_node Positive terminal node index.
     * @param negative_node Negative terminal node index.
     * @param value Numerical component value.
     */
    PassiveComponent(
        std::string name,
        int32_t positive_node,
        int32_t negative_node,
        double value
    )
        : name(name),
          positive_node(positive_node),
          negative_node(negative_node),
          value(value)
    {
    }
};