#pragma once

/**
 * ============================================================================
 *  Project        : Linear Circuit Simulator
 *  File           : simulation_runner.hpp
 *
 *  Description
 *  --------------------------------------------------------------------------
 *  This file implements the high-level simulation workflow of the simulator.
 *
 *  The SimulationRunner acts as a dispatcher between the parsed Netlist and
 *  the available simulation backends.
 *
 *  Depending on the selected analysis type, the runner creates all required
 *  matrix representations, solver objects and result exporters.
 *
 *      Parsed Netlist
 *            ↓
 *      SimulationRunner
 *            ├─ Operating Point Analysis
 *            ├─ AC Analysis
 *            └─ Transient Analysis
 *
 *  Mathematical Background
 *  --------------------------------------------------------------------------
 *
 *  Operating Point Analysis:
 *
 *      Gx = b
 *
 *  AC Analysis:
 *
 *      G(jω)x = b
 *
 *  Transient Analysis:
 *
 *      Cx' + Gx = b
 *
 *  Each analysis type requires a different matrix formulation and solver.
 *  This class selects the appropriate workflow and executes the complete
 *  simulation pipeline.
 *
 *  Design Notes
 *  --------------------------------------------------------------------------
 *
 *  The simulation is intentionally executed inside the constructor.
 *
 *  Creating a SimulationRunner object indicates that the simulation should
 *  immediately start and run to completion. Therefore no separate run()
 *  function is required.
 *
 *  Author         : Felix Zenhäusern
 *  Created        : 2026
 *  License        : MIT License
 * ============================================================================
 */

#include <cmath>
#include <iostream>

#include "netlist.hpp"
#include "simulation_results.hpp"
#include "result_exporter.hpp"

// Transient analysis
#include "mna_system_tran.hpp"
#include "build_mna_tran.hpp"
#include "statespace_model_tran.hpp"
#include "statespace_creator_tran.hpp"
#include "solver_tran.hpp"

// Operating point analysis
#include "mna_system_op.hpp"
#include "build_mna_op.hpp"
#include "solver_op.hpp"

// AC analysis
#include "mna_system_ac.hpp"
#include "build_mna_ac.hpp"
#include "solver_ac.hpp"

/**
 * @brief Executes the complete simulation workflow.
 *
 * The constructor inspects the analysis mode stored in the netlist and
 * delegates execution to the corresponding solver pipeline.
 */
class SimulationRunner
{
private:

    /**
     * Complete circuit description generated by the parser.
     */
    Netlist* netlist{nullptr};

    /**
     * Stores simulation metadata and timing information.
     */
    SimulationResults* simulation_result{nullptr};

    /**
     * Responsible for exporting simulation results.
     */
    ResultExporter* output{nullptr};

public:

    /**
     * @brief Runs the complete simulation.
     *
     * @param netlist Parsed circuit and simulation configuration.
     * @param simulation_result Container used to store simulation metadata.
     * @param output Result exporter used for CSV generation and logging.
     */
    SimulationRunner(
        Netlist* netlist,
        SimulationResults* simulation_result,
        ResultExporter* output
    )
        : netlist(netlist),
          simulation_result(simulation_result),
          output(output)
    {
        /*
         * =====================================================================
         * Operating Point Analysis
         * =====================================================================
         *
         * Solve the static MNA equation system
         *
         *      Gx = b
         *
         * Dynamic energy storage elements are evaluated in their steady-state
         * equivalent representation.
         */
        if (netlist->analysis == Analysis::op)
        {
            /*
             * The operating point equation system contains:
             *
             *      - Node voltages
             *      - Independent voltage source currents
             *      - Inductor currents
             */
            netlist->order_mna_equation =
                netlist->num_nodes +
                netlist->num_voltage_sources +
                netlist->num_inductors;

            /*
             * Allocate sparse MNA matrices and vectors.
             */
            MnaSystemOp mna_equation(netlist);

            /*
             * Stamp all circuit components into the sparse MNA system.
             */
            MnaBuilderOp create_mna(
                &mna_equation,
                netlist
            );

            /*
             * Solve the linear equation system and export results.
             */
            SolverOp solution(
                netlist,
                &mna_equation,
                simulation_result,
                output
            );
        }

        /*
         * =====================================================================
         * Transient Analysis
         * =====================================================================
         *
         * Solve the dynamic system
         *
         *      Cx' + Gx = b
         *
         * by converting the MNA representation into a reduced state-space model.
         */
        else if (netlist->analysis == Analysis::tran)
        {
            /*
             * A transient simulation requires at least one energy storage
             * element. Otherwise no dynamic state exists.
             */
            if (netlist->num_capacitors == 0 &&
                netlist->num_inductors == 0)
            {
                std::cout
                    << "Transient analysis requires at least one "
                    << "capacitor or inductor."
                    << std::endl;

                return;
            }

            netlist->order_mna_equation =
                netlist->num_nodes +
                netlist->num_voltage_sources +
                netlist->num_inductors;

            /*
             * Build the continuous-time MNA representation.
             */
            MnaSystemTran mna_equation(netlist);

            /*
             * Assemble conductance matrix G, storage matrix C and
             * excitation vector b.
             */
            MnaBuilderTran create_mna(
                &mna_equation,
                netlist
            );

            /*
             * Reduced state-space representation:
             *
             *      z' = Fz + g
             */
            StateSpaceModel state_space;

            /*
             * Convert the differential-algebraic MNA system into a
             * state-space model suitable for numerical integration.
             */
            StateSpaceCreator state_space_creator(
                netlist,
                &state_space,
                &mna_equation
            );

            /*
             * Perform transient simulation and export all sampled results.
             */
            SolverTran solution(
                netlist,
                &mna_equation,
                &state_space,
                simulation_result,
                output
            );
        }

        /*
         * =====================================================================
         * AC Analysis
         * =====================================================================
         *
         * Perform a frequency sweep and solve the complex-valued MNA system
         * for every frequency sample.
         */
        else if (netlist->analysis == Analysis::ac)
        {
            /*
             * AC analysis introduces additional variables only for
             * independent voltage sources.
             */
            netlist->order_mna_equation =
                netlist->num_nodes +
                netlist->num_voltage_sources;

            /*
             * Generate logarithmically spaced frequency samples.
             *
             * Example:
             *
             *      1 Hz
             *      10 Hz
             *      100 Hz
             *      1 kHz
             *
             * This corresponds to the standard SPICE decade sweep.
             */
            const int num_calculations =
                (log10(netlist->f_end) -
                 log10(netlist->f_start))
                * netlist->n;

            /*
             * Allocate the complex-valued MNA system.
             */
            MnaSystemAc mna_equation(netlist);

            /*
             * Create the AC matrix builder. The matrix is updated for each
             * frequency because capacitors and inductors are frequency
             * dependent components.
             */
            MnaBuilderAc create_mna(
                &mna_equation,
                netlist
            );

            /*
             * Create the AC solver responsible for exporting magnitude and
             * phase information.
             */
            SolverAc solution(
                netlist,
                &mna_equation,
                simulation_result,
                output
            );

            /*
             * Evaluate the circuit response for each frequency sample.
             *
             * For every frequency:
             *
             *      1. Update reactive component models
             *      2. Assemble the complex MNA matrix
             *      3. Solve the equation system
             *      4. Export magnitude and phase
             */
            for (int i = 0; i < num_calculations; ++i)
            {
                const double current_frequency =
                    std::pow(
                        10.0,
                        (static_cast<double>(i) /
                         static_cast<double>(netlist->n))
                        + log10(netlist->f_start)
                    );

                /*
                 * Convert frequency into angular frequency:
                 *
                 *      ω = 2πf
                 */
                create_mna.update_mna(
                    current_frequency * 2.0 * M_PI
                );

                /*
                 * Solve the updated MNA system and store results.
                 */
                solution.update_solution(
                    current_frequency,
                    i
                );
            }
        }

        /*
         * Future analysis types may be added here.
         */
        else
        {
            std::cout
                << "Unsupported analysis type."
                << std::endl;
        }
    }
};